### ISSUE TITLE
Time to release a stable version?

### ISSUE THREAD

**Issue by bobvandevijver** [angel-vladov/select2-theme-bootstrap4#11]
I'm using this theme already for years, and it works beautifully. I just tried another [theme](https://www.npmjs.com/package/select2-bootstrap4-theme) as I prefer to use stable versions in my projects, but that theme just isn't it.

Isn't it already time to release a stable version?

**Comment by angel-vladov** [comment]
The idea behind this theme was to merge in the original select2 repo. It doesn't seem like a thing that will happen soon.

I will publish it as a stable version in the next release.

**Comment by angel-vladov** [comment]
Version is bumped to 1.0.0
There are some minor changes to the build process. The generated CSS is identical with the previous beta version.
