### ISSUE TITLE
Migration to Bootstrap 5

### ISSUE THREAD

**Issue by florianlacreuse** [angel-vladov/select2-theme-bootstrap4#14]
Thanks again for your job with this Select2 Bootstrap 4 theme.

Are you planning to do it again for Bootstrap 5? Currently in beta, BS 5 final release should be available soon.

**Comment by angel-vladov** [comment]
Yes. I'll create another version once Bootstrap 5 is out. This time I'll wait for the final version first. 

_They did quite a few changes between the Bootstrap 4 betas and the final release._

**Comment by florianlacreuse** [comment]
That's great news, thanks!

**Comment by florianlacreuse** [comment]
Are you still planning to work on a version for Bootstrap 5?

**Comment by angel-vladov** [comment]
Yes. I plan on doing that in 1 or 2 months when I start my first Bootstrap 5 project. 
I'm sorry if you need that urgently.

**Comment by florianlacreuse** [comment]
Sorry to bother you again, but it's just to know if you finally got the opportunity to work on a Bootstrap 5 theme?
This is free open source world, you owe nothing to anyone. :) I'm just asking to know if it can happen one day.
Your work for Bootstrap 4 was awesome, thanks again for that!

**Comment by angel-vladov** [comment]
Hey, I did some work with Bootstrap 6, I plan on releasing the theme for BS 5, but this will probably happen end of this month or next month. I started updating the styles but there's still more work to do.

**Comment by angel-vladov** [comment]
The BS5 version will be another repo, I'll name it `select2-theme-bootstrap5`. There are probably people using wildcard for importing this BS4 theme, I don't want to break their project.

I'll ping you here when I'm ready and have the first version published in `npm`

**Comment by angel-vladov** [comment]
@florianlacreuse you can find the current progress here - https://github.com/angel-vladov/select2-theme-bootstrap5

_Keep in mind that is still work in progress, and it's not properly tested yet. I haven't updated the README file as well._

**Comment by angel-vladov** [comment]
You can find the select2 bs5 theme here
Git - https://github.com/angel-vladov/select2-theme-bootstrap5
NPM - https://www.npmjs.com/package/select2-theme-bootstrap5

This is a `pre-release` version. Please let me know if you find any bugs.

**Comment by florianlacreuse** [comment]
Thank you, that was quick! I'll look into it as soon as possible. I'll create issues or PR if needed.
