### ISSUE TITLE
Deprecation warning when compiling with recent sass

### ISSUE THREAD

**Issue by mpibpc-mroose** [angel-vladov/select2-theme-bootstrap4#16]
When compiling the source with `sass 1.43.4 compiled with dart2js 2.14.4 ` I get some deprecation warnings like this:

```
Deprecation Warning: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($spacer, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
718 │ $navbar-padding-y:                  $spacer / 2 !default;
    │                                     ^^^^^^^^^^^
```

To avoid breaking the compile I recommend to fix those definitions.

**Comment by angel-vladov** [comment]
Released version 1.0.1 replacing all division by 2 with `* .5`
This will ensure compatibility with old libsass and support the newer dart based sass compiler
